version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Foox
          command: npx patch-package lodash
      - run:
          name: Typings fix
          command: mkdir /home/circleci/.dts/perf -p    
      - run:
          name: Test
          command: yarn cover   
      - run:
          name: Upload
          command: bash <(curl -s https://codecov.io/bash)   
      - save-npm-cache
  save-npm-cache:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  node-base:
    docker:
      - image: node:10
    steps:
      - test-nodejs
  node-middle:
    docker:
      - image: node:12
    steps:
      - test-nodejs
  node-latest:
    docker:
      - image: node:14
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-base
      - node-middle
      - node-latest
